apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 namespace: default
 name: deploy-app-binding

subjects:
 - kind: ServiceAccount
   name: svacc1
   apiGroup: ""
roleRef:
 kind: Role
 name: pod-reader
 apiGroup: ""
